<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 2,
                'first_name' => 'new',
                'last_name' => 'new',
                'email' => 'new@new.com',
                'depart' => 'new',
                'position' => 'all',
                'password' => '$2y$10$wfKk7SLpVWmi/6/2kZm7y.pVJ762hevpGndGGF2TJ8r2Hi3xoJ89m',
                'employee_id' => 'new',
                'permissions' => NULL,
                'last_login' => '2018-05-08 14:50:45',
                'created_at' => '2017-10-17 17:20:48',
                'updated_at' => '2018-05-08 14:50:45',
                'logstatus' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'first_name' => 'hello',
                'last_name' => 'hello',
                'email' => 'admin@admin',
                'depart' => 'total',
                'position' => 'admin',
                'password' => '$2y$10$X05F/pK6q2mlP2wmqzSR6.j7ktpTuVGfFZRhj93.O70yOL2nDRUl.',
                'employee_id' => '54',
                'permissions' => NULL,
                'last_login' => '2019-01-28 23:58:51',
                'created_at' => '2017-10-17 18:21:16',
                'updated_at' => '2019-01-29 02:18:47',
                'logstatus' => 2,
            ),
            2 => 
            array (
                'id' => 4,
                'first_name' => 'newdoc',
                'last_name' => 'doc',
                'email' => 'doc@doc.com',
                'depart' => 'doc',
                'position' => 'doctor',
                'password' => '$2y$10$6iu1YDH6Lj01Vchi6ifRmuSAyCITRl0gQZ2vcRcLeVMjSBZ7o/Fv6',
                'employee_id' => '22002',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-17 18:23:43',
                'updated_at' => '2017-10-17 18:23:43',
                'logstatus' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'first_name' => 'baby',
                'last_name' => 'baby',
                'email' => 'baby@baby.com',
                'depart' => '2',
                'position' => 'baby',
                'password' => '$2y$10$5ohmEkou9MmLN/BNAukeGeXotHTzktj6J3JR85ur/2nwr65cleApq',
                'employee_id' => 'baby',
                'permissions' => NULL,
                'last_login' => '2018-09-27 20:01:11',
                'created_at' => '2017-10-17 18:51:11',
                'updated_at' => '2018-09-27 20:01:11',
                'logstatus' => 1,
            ),
            4 => 
            array (
                'id' => 6,
                'first_name' => 'try',
                'last_name' => 'try',
                'email' => 'try@kfkf',
                'depart' => 'try',
                'position' => 'try',
                'password' => '$2y$10$KHxRTn4ejGJfsCUEXAjzZuSb7PTY1jRZMTki4Ou0zqmGyyw2zjY8u',
                'employee_id' => 'try',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-17 19:01:38',
                'updated_at' => '2017-10-17 19:01:38',
                'logstatus' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'first_name' => 'new',
                'last_name' => 'nurse',
                'email' => 'hinurse@hi.com',
                'depart' => 'clinical',
                'position' => 'all',
                'password' => '$2y$10$Z.h9tasQXqJ5RwWhxCnHXeZeD/bj9/yHHaEzGhfcj8uROpL/pZSDG',
                'employee_id' => '3030',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-17 19:39:12',
                'updated_at' => '2017-10-17 19:39:12',
                'logstatus' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'first_name' => 'viveksah',
                'last_name' => 'kumar',
                'email' => 'vibe@vibe.com',
                'depart' => 'admin',
                'position' => 'admin',
                'password' => '$2y$10$P0SMqwHKA4urNUrV7nv.K.5apUmpXkdG.ng8kMC7yd9GSeTzUSKmW',
                'employee_id' => '565',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-17 19:56:13',
                'updated_at' => '2017-10-17 19:56:13',
                'logstatus' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'first_name' => 'hellow',
                'last_name' => 'dlks',
                'email' => 'first@first.com',
                'depart' => 'kasfk',
                'position' => 'admin',
                'password' => '$2y$10$7zUCExW5kfS.o1TfgGcleuNCM0w2xzcTeycv2RGTHJ2ew0.5k.cmC',
                'employee_id' => 'akfkks',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-19 15:59:10',
                'updated_at' => '2017-10-19 15:59:10',
                'logstatus' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'first_name' => 'nurse2',
                'last_name' => 'nurse2',
                'email' => 'viveksah2sah@gmail.co',
                'depart' => 'nurse',
                'position' => 'nurse',
                'password' => '$2y$10$fdP8TI0t654B29fSG/a6Q.WIz3EsxY2lHmuHaRGAgT0hLEXSlkomq',
                'employee_id' => 'nurse',
                'permissions' => NULL,
                'last_login' => '2017-10-29 14:26:11',
                'created_at' => '2017-10-20 11:19:11',
                'updated_at' => '2017-10-29 14:26:11',
                'logstatus' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'first_name' => 'emailcheck',
                'last_name' => 'check',
                'email' => 'gadacaw@axsup.net',
                'depart' => 'admin',
                'position' => 'admin',
                'password' => '$2y$10$aW0IETZm03ezI4/C8Icp4OxJYDiDywwXtVdtuLq/YaQgOOPrMcFR.',
                'employee_id' => 'admin',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-20 20:26:15',
                'updated_at' => '2017-10-20 20:26:15',
                'logstatus' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'first_name' => 'emailcheck',
                'last_name' => 'check',
                'email' => 'deledubiy@zhorachu.com',
                'depart' => 'admin',
                'position' => 'admin',
                'password' => '$2y$10$TUxq/R1XgKxcqnkF.yXsa.BteQyy0pPKliOjBgbleOJQxjkGoxcSe',
                'employee_id' => 'admin',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-20 20:22:27',
                'updated_at' => '2017-10-20 20:22:27',
                'logstatus' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
                'first_name' => 'bjfblkfgnslk',
                'last_name' => 'kfgkgk',
                'email' => 'pabufeda@axsup.net',
                'depart' => 'dldl',
                'position' => 'addmin',
                'password' => '$2y$10$QPCw7ZVHSZhGD5uN4Qe0auKzRRwayNy8IGEkgEd9QjuTMERoLvnGe',
                'employee_id' => 'dkk',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-23 11:25:52',
                'updated_at' => '2017-10-23 11:25:52',
                'logstatus' => NULL,
            ),
            12 => 
            array (
                'id' => 18,
                'first_name' => 'newemp',
                'last_name' => 'newemp',
                'email' => 'heto@nezdiro.org',
                'depart' => 'hi',
                'position' => 'admin',
                'password' => '$2y$10$v.k7WkqWEfvSs0XNVGO0B.YcgZ/TZAyBUB5.ZDzz6FUlupgIn1wtW',
                'employee_id' => 'hi',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-23 11:27:37',
                'updated_at' => '2017-10-23 11:27:37',
                'logstatus' => NULL,
            ),
            13 => 
            array (
                'id' => 19,
                'first_name' => 'final',
                'last_name' => 'hellow',
                'email' => 'dojum@axsup.net',
                'depart' => 'new',
                'position' => 'admin',
                'password' => '$2y$10$9VPrjkemK2kFwDrKHAYYrO47C8sC.RBC21SjTRQCbeqgtJbS2kMSi',
                'employee_id' => 'new',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-23 11:43:46',
                'updated_at' => '2017-10-23 11:43:46',
                'logstatus' => NULL,
            ),
            14 => 
            array (
                'id' => 20,
                'first_name' => 'big',
                'last_name' => 'big',
                'email' => 'wimicano@payperex2.com',
                'depart' => 'jshs',
                'position' => 'admin',
                'password' => '$2y$10$x0i6PtGIU1nJVLYtUWCnqOc61UzNVeJHakkrOuE8Ca2t9zpB1u4Ae',
                'employee_id' => '72727',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-23 11:50:56',
                'updated_at' => '2017-10-23 11:50:56',
                'logstatus' => NULL,
            ),
            15 => 
            array (
                'id' => 21,
                'first_name' => 'big',
                'last_name' => 'big',
                'email' => 'tarebi@datum2.com',
                'depart' => 'jshs',
                'position' => 'admin',
                'password' => '$2y$10$bcaKslUCeXA2jgIS/A8se.Z4CpT.Twe6E/ga8Jc33DkblVspSUN1W',
                'employee_id' => '72727',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-23 11:54:37',
                'updated_at' => '2017-10-23 11:54:37',
                'logstatus' => NULL,
            ),
            16 => 
            array (
                'id' => 22,
                'first_name' => 'nick',
                'last_name' => 'nick',
                'email' => 'rutaju@geronra.com',
                'depart' => 'admin',
                'position' => 'admin',
                'password' => '$2y$10$oa8NNiwaGU3UFm.YDj3K4e6O6UKGWVVKZoJURfHsbmBqSr.78A4GC',
                'employee_id' => 'admin',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2017-10-23 13:03:51',
                'updated_at' => '2017-10-23 13:03:51',
                'logstatus' => NULL,
            ),
            17 => 
            array (
                'id' => 23,
                'first_name' => 'vibejek',
                'last_name' => 'sah',
                'email' => 'viveksah2sah@gmail.com',
                'depart' => 'nurse',
                'position' => 'admin',
                'password' => '$2y$10$AzwC5wja5T0Yx7DzXEVGiev8TdSNqFFa.Hyr2J500LdktpQVx.0vy',
                'employee_id' => 'ldkdsk',
                'permissions' => NULL,
                'last_login' => '2018-06-06 14:21:15',
                'created_at' => '2018-05-29 16:13:53',
                'updated_at' => '2018-06-06 14:21:15',
                'logstatus' => 1,
            ),
            18 => 
            array (
                'id' => 25,
                'first_name' => 'sdcsdds',
                'last_name' => 'asd',
                'email' => 'depu@fidelium10.com',
                'depart' => '12',
                'position' => 'admin',
                'password' => '$2y$10$gxAIq5XdtxU9nAbvyYOwUeyolnTyiwE5p6zoRZkDZJ8Cx0eJxy7ce',
                'employee_id' => '21342343543',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2018-08-26 12:36:45',
                'updated_at' => '2018-08-26 12:36:45',
                'logstatus' => NULL,
            ),
            19 => 
            array (
                'id' => 27,
                'first_name' => 'sdcsdds',
                'last_name' => 'ddsdsfds',
                'email' => 'dowuzi@fidelium10.com',
                'depart' => '12',
                'position' => 'admin',
                'password' => '$2y$10$d4VHHyWLRuMAzTEDn2/tQeQ0FwPij/xS88HC7obK9t6EByFTNzH46',
                'employee_id' => 'xcsdxcx',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2018-08-26 12:40:28',
                'updated_at' => '2018-08-26 12:40:28',
                'logstatus' => NULL,
            ),
            20 => 
            array (
                'id' => 28,
                'first_name' => 'sdcsdds',
                'last_name' => 'sdssd',
                'email' => 'cetura@travala10.com',
                'depart' => '1',
                'position' => 'admin',
                'password' => '$2y$10$GlRv4Uvhrsg8Wkf/zcJbQuSDrN1DT86JCHslp0vSzFWSj8hSObbse',
                'employee_id' => '21342343543',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2018-08-26 12:42:35',
                'updated_at' => '2018-08-26 12:42:35',
                'logstatus' => NULL,
            ),
            21 => 
            array (
                'id' => 29,
                'first_name' => 'sdcsdds',
                'last_name' => 'sdcsdds',
                'email' => 'taho@1shivom.com',
                'depart' => '12',
                'position' => 'dsfsdfdsf',
                'password' => '$2y$10$3Jt66yMfCDO0T7Oxd9tE7.Rz749ZCybaqJXtK57j6pnG8isqNnML6',
                'employee_id' => 'xcsdxcx',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2018-08-26 12:45:05',
                'updated_at' => '2018-08-26 12:45:05',
                'logstatus' => NULL,
            ),
            22 => 
            array (
                'id' => 30,
                'first_name' => 'vivewmekl',
                'last_name' => 'sdsfds',
                'email' => 'bivebot@bit-degree.com',
                'depart' => '1',
                'position' => 'nurse-fornt-office',
                'password' => '$2y$10$lao05DTR5J1YVIL9WJcCOOumrO/H5bLSAjSAjBybxEv4PivF9UsMG',
                'employee_id' => 'fdfçlgkçld',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2018-08-26 20:44:45',
                'updated_at' => '2018-08-26 20:44:45',
                'logstatus' => NULL,
            ),
            23 => 
            array (
                'id' => 31,
                'first_name' => 'fjghkdlfj',
                'last_name' => 'ssdds',
                'email' => 'xodixufom@hurify1.com',
                'depart' => '1',
                'position' => 'front-operator',
                'password' => '$2y$10$.GzfWvfmhHufmKOtIexmV.oDR3aWl4iD6bQudXJ38j2FFEojS5XT6',
                'employee_id' => 'dsopkfodsk',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2018-08-29 15:50:30',
                'updated_at' => '2018-08-29 15:50:30',
                'logstatus' => NULL,
            ),
            24 => 
            array (
                'id' => 32,
                'first_name' => 'sdcsdds',
                'last_name' => 'asd',
                'email' => 'yugo@travala10.com',
                'depart' => '12',
                'position' => 'front-operator',
                'password' => '$2y$10$KcklrWVsQPUq8/9kaSnJGOQ4wnSDENztfEvDWUHHFJiFF4uVU.40O',
                'employee_id' => 'dfdsfdsfd',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2018-08-30 12:58:10',
                'updated_at' => '2018-08-30 12:58:10',
                'logstatus' => NULL,
            ),
            25 => 
            array (
                'id' => 34,
                'first_name' => 'sdfdsmçl,',
                'last_name' => 'ddsdsfds',
                'email' => 'cezetaba@poly-swarm.com',
                'depart' => '3',
                'position' => 'doctor',
                'password' => '$2y$10$7VEKLkIh2VCGLww2.p.mH.uiTNZoW6UkEvDSngfPLcEY/BM0uGm1.',
                'employee_id' => '545455',
                'permissions' => NULL,
                'last_login' => NULL,
                'created_at' => '2018-08-31 01:13:30',
                'updated_at' => '2018-08-31 01:13:30',
                'logstatus' => NULL,
            ),
        ));
        
        
    }
}